apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ykcumven0-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ykcumven0-java-springboot-gitops